name: Checksum adder

on: [push, workflow_dispatch]
jobs:
  add-checksum:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          bash Scripts/AddChecksum.sh 
      - name: switching from HTTPS to SSH
        run: git remote set-url origin https://github.com/sopho-s/Talk
      - name: check for changes
        run: git status
      - name: stage changed files
        run: git add .
      - name: login
        run: |
          git config --global user.email "woodsnicholas01@gmail.com"
          git config --global user.name "sopho-s"
      - name: commit changed files
        run: git commit -m "Auto adding checksum"
      - name: fetch from main
        run: git fetch origin main
      - name: push code to main
        run: git push origin HEAD:main
